---
- name: Determine partition device names
  vars:
    prefix: '{{
           "-part" if drive is regex("^/dev/disk/by-id")
      else "p"     if drive is regex("^/dev/nvme")
      else ""
  }}'
  set_fact:
    device_boot: '{{ drive }}{{ prefix }}1'
    device_luks: '{{ drive }}{{ prefix }}2'
