---
- name: Setup Arch Linux
  hosts: localhost
  roles:
   - name: user_creation
  tasks:
   - name: Install packages
     community.general.pacman:
       name: 
        - plasma
        - kde-applications
        - firefox
       state: present