---
- name: Setup Arch Linux
  hosts: dev
  connection: local
  roles:
   - name: user_creation
   - name: autologin
  tasks:
   - name: Install packages
     community.general.pacman:
       name: 
        - hyprland
        - kitty
        - firefox
        - swaync
        - pipewire
        - wireplumber
        - xdg-desktop-portal-hyprland
        - polkit-kde-agent
        - qt5-wayland
        - qt6-wayland
        - neovim
        - man
        - less
        - wofi
       state: present

