---
- name: Setup Arch Linux
  hosts: localhost
  roles:
   - name: user_creation
  tasks:
   - name: Install packages
     community.general.pacman:
       name: 
        - hyprland
        - kitty
        - firefox
        - swaync
        - pipewire
        - wireplumber
        - xdg-desktop-portal-hyprland
        - polkit-kde-agent
        - qt5-wayland
        - qt6-wayland
       state: present