---
- name: Create 'IWD' configuration directories
  ansible.builtin.file:
    path: '{{ arch_mnt }}{{ item.path }}'
    state: directory
    owner: root
    group: root
    mode: '{{ item.mode }}'
  loop:
    - { path: '/etc/iwd',     mode: '0755' }
    - { path: '/var/lib/iwd', mode: '0700' }
  loop_control:
    label: '{{ item.path }}'

- name: Copy 'IWD' configuration
  ansible.builtin.copy:
    dest: '{{ arch_mnt }}/etc/iwd/main.conf'
    content: |
      [General]
      EnableNetworkConfiguration=true

      [Network]
      NameResolvingService=systemd
      RoutePriorityOffset=20
    owner: root
    group: root
    mode: 0644
  notify: '{{ "enable" if bootstrap else "restart" }}_iwd'
