---
- name: Create directory '/etc/systemd/timesync.conf.d'
  ansible.builtin.file:
    path: '{{ arch_mnt }}/etc/systemd/timesyncd.conf.d'
    state: directory
    owner: root
    group: root
    mode: 0755

- import_tasks: ntp_servers.yml
- import_tasks: ntp_fallback.yml
