---
- name: Set cache pressure
  ansible.posix.sysctl:
    name: vm.vfs_cache_pressure
    value: '{{ vfs_cache_pressure | default(100) }}'
    state: present
    sysctl_file: '{{ arch_mnt }}/etc/sysctl.d/50-swappiness.conf'
    reload: '{{ "no" if bootstrap else "yes" }}'
