---
- name: Ensure sudo and openssh are installed
  community.general.pacman:
    name: 
     - sudo
     - openssh
    state: present
- name: Ensure group "sudo" exists
  ansible.builtin.group:
    name: sudo
    state: present
- name: Add the specified user, appending the group 'sudo' to the user's groups
  ansible.builtin.user:
    name: '{{ username }}'
    groups: sudo
    append: yes
    create_home: yes
    generate_ssh_key: yes
    password: '{{ user_password }}'