---
- name: Configure ethernet interface for DHCP
  ansible.builtin.copy:
    dest: '{{ arch_mnt }}/etc/systemd/network/ethernet.network'
    content: |
      [Match]
      Name={{ ethernet_interface }}

      [Network]
      DHCP=yes
      LLMNR=no

      [DHCPv4]
      UseHostname=no
      RouteMetric=10

      [DHCPv6]
      UseHostname=no
      RouteMetric=10
    owner: root
    group: root
    mode: 0644
  notify: '{{ "enable" if bootstrap else "reload" }}_networkd'
