---
- name: Configure '/etc/hosts'
  ansible.builtin.copy:
    dest: '{{ arch_mnt }}/etc/hosts'
    content: |
      # Static table lookup for hostnames.
      # See hosts(5) for details.

      127.0.0.1  localhost
      {{ hostip | default('127.0.1.1') }}  {{ hostname | default(inventory_hostname_short) }}

      ::1        localhost {{ hostname | default(inventory_hostname_short) }} ip6-localhost ip6-loopback
      fe00::0    ip6-localnet
      ff00::0    ip6-mcastprefix
      ff02::1    ip6-allnodes
      ff02::2    ip6-allrouters
    owner: root
    group: root
    mode: 0644
