---
- name: Configure SSH server
  ansible.builtin.lineinfile:
    path: '{{ arch_mnt }}/etc/ssh/sshd_config'
    regexp: '{{ item.regex }}'
    line: '{{ item.line }}'
    state: present
    owner: root
    group: root
    mode: 0600
  loop:
    - { regex: '^#?\s*Port\s',                   line: Port 22 }
    - { regex: '^#?\s*PubkeyAuthentication\s',   line: PubkeyAuthentication yes }
    - { regex: '^#?\s*PasswordAuthentication\s', line: PasswordAuthentication yes }
    - { regex: '^#?\s*PermitEmptyPasswords\s',   line: PermitEmptyPasswords no }
    - { regex: '^#?\s*PermitRootLogin\s',        line: PermitRootLogin yes }
    - { regex: '^#?\s*AllowUsers\s',             line: AllowUsers root }
    - { regex: '^#?\s*Banner\s',                 line: Banner /etc/issue.net }
    - { regex: '^#?\s*ClientAliveInterval\s',    line: ClientAliveInterval 300 }
    - { regex: '^#?\s*Compression\s',            line: Compression no }
    - { regex: '^#?\s*TCPKeepAlive\s',           line: TCPKeepAlive no }
    - { regex: '^#?\s*AllowAgentForwarding\s',   line: AllowAgentForwarding no }
    - { regex: '^#?\s*AllowTcpForwarding\s',     line: AllowTcpForwarding no }
    - { regex: '^#?\s*ClientAliveCountMax\s',    line: ClientAliveCountMax 2 }
    - { regex: '^#?\s*MaxAuthTries\s',           line: MaxAuthTries 3 }
    - { regex: '^#?\s*MaxSessions\s',            line: MaxSessions 2 }
    - { regex: '^#?\s*LogLevel\s',               line: LogLevel VERBOSE }
  loop_control:
    label: '{{ item.line }}'
  notify: '{{ "enable" if bootstrap else "reload" }}_openssh_server'
